Repository Mastercard/community-pass-react-native-wrapper, pull requests merged in 2023-04, with the labels that each got.

#3 fix: clean up npm vulnerabilities
  CompassRNSampleApp/package-lock.json
  CompassRNSampleApp/yarn.lock
  package-lock.json
Labels: bug

#5 implement getRegistrationData API
  CompassRNSampleApp/yarn.lock
  android/src/main/AndroidManifest.xml
  android/src/main/java/com/mastercard/compass/cp3/lib/react_native_wrapper/CompassLibraryReactNativeWrapperModule.kt
  android/src/main/java/com/mastercard/compass/cp3/lib/react_native_wrapper/route/GetRegistrationDataAPIRoute.kt
  android/src/main/java/com/mastercard/compass/cp3/lib/react_native_wrapper/ui/GetRegistrationDataCompassApiHandlerActivity.kt
  docs/api-references/README.md
  docs/api-references/device-lifecycle-management-api.md
  src/index.ts
  yarn.lock
Labels: enhancement

#13 Ft/get verify passcode
  TODO.md
  android/src/main/AndroidManifest.xml
  android/src/main/java/com/mastercard/compass/cp3/lib/react_native_wrapper/CompassLibraryReactNativeWrapperModule.kt
  android/src/main/java/com/mastercard/compass/cp3/lib/react_native_wrapper/route/GetVerifyPasscodeAPIRoute.kt
  android/src/main/java/com/mastercard/compass/cp3/lib/react_native_wrapper/ui/GetVerifyPasscodeCompassApiHandlerActivity.kt
  docs/api-references/user-lifecycle-management-api.md
  src/index.ts
Labels: documentation, enhancement

#16 Ft/get user verification
  TODO.md
  android/src/main/AndroidManifest.xml
  android/src/main/java/com/mastercard/compass/cp3/lib/react_native_wrapper/CompassLibraryReactNativeWrapperModule.kt
  android/src/main/java/com/mastercard/compass/cp3/lib/react_native_wrapper/route/GetUserVerificationAPIRoute.kt
  android/src/main/java/com/mastercard/compass/cp3/lib/react_native_wrapper/ui/GetUserVerificationCompassApiHandlerActivity.kt
  docs/api-references/user-lifecycle-management-api.md
  src/index.ts
Labels: documentation, enhancement
